### ISSUE TITLE
P1. In v1 filter tchap users based on their domain name

### ISSUE THREAD

**Issue by pedevineau** [etalab-ia/albert-tchapbot#15]
If a user is not in the domain name, tell him/her only some administrations have access to Albert Tchap right now. Still new administrations will gain access to it in next weeks.

Domain main appears in matrix metadata
For first version, see the table of domains by @bolinocroustibat

**Comment by bolinocroustibat** [comment]
The allowed user email domains for the beta test should be:
- mail.numerique.gouv.fr
- modernisation.gouv.fr
- data.gouv.fr
- beta.gouv.fr

This should be configurable in a config file ideally.

If the user email is not part of this domain, an automatic message should be sent to the user, saying:
"_**Albert Tchap Bot is not available for your domain yet. Please stay in touch, it will come to you after a beta test!**_"

**Comment by bolinocroustibat** [comment]
PR: https://github.com/etalab-ia/albert-tchapbot/pull/17

**Comment by Naxxos** [comment]
Yesterday, there was also a discussion about allowing access to pm.gouv.fr. I believe the total number of potential participants could range between 1 000 and 2 000.

**Comment by bolinocroustibat** [comment]
@Naxxos ok, let me know if we should allow this domain as well.
