### ISSUE TITLE
Hide all commands related to sources and rag when in a no-rag mode

### ISSUE THREAD

**Issue by bolinocroustibat** [etalab-ia/albert-tchapbot#33]
After some user feedbacks from French administrations, it appears most first use cases don't use RAG features. 
We might have to deploy a non-RAG Albert Tchap bot, or at least be able to switch often to a non-RAG mode.

When in a non-rag mode, we need to hide the rag/sources related command.

(discussed with @Naxxos )

**Comment by dtrckd** [comment]
Can we add a command `!rag` to simply switch between RAG and no-RAG mode, to start ?
If not in rag mode.

Like so, there is no need to deploy another bot.

**Comment by bolinocroustibat** [comment]
> Can we add a command !rag to simply switch between RAG and no-RAG mode, to start ?

We could definitely do that, but we already have the `!mode` command to switch to another mode including a non-rag one, no? Isn't that sufficient?
Another solution would be to condition the availability of the `!sources` command depending on the mode.

**Comment by bolinocroustibat** [comment]
> Yes that's true. To make that work agnostically, we could add a route in the backend (it could be a modifications of the api/v2/models) in order to return, in addition to the model names, the supported modes and whether they are RAG or not.

That would indeed be ideal and the more future-proof option
