### ISSUE TITLE
Redirect errors

### ISSUE THREAD

**Issue by bolinocroustibat** [etalab-ia/albert-tchapbot#9]
Don't redirect errors to chat as it is, but replace them with a generic error message saying that Albert is under testing and/or maintenance. With possibly a hidden !debug command to enable/disable their redirection.

As suggested by @nrolin we can also send back a message to the user and dump the logs in a room with just the devs (it's very easy to do from a tchap bot, you might as well take advantage of it 🤷)

**Comment by dtrckd** [comment]
Wouldn't be good to handle several error type instead of having just one general one ? like
- off because maintenance
- off because server error - we could catch some specific ones as we go along.

I mean, why say it is a maintenance error while it's like the user send an unsupported file ?

**Comment by bolinocroustibat** [comment]
@dtrckd Totally agree.

**Comment by bolinocroustibat** [comment]
@dtrckd The related PR: https://github.com/etalab-ia/albert-tchapbot/pull/18

As it is a quite urgent feature before putting it back into production, this doesn't take your suggestion into account yet. If you have time to add the two different cases for different Albert API errors on the same PR quickly, please don't hesitate. Otherwise I suggest we do it in a separate PR so we can merge this feature ASAP.
